version: ~> 1.0

import:
  - silverstripe/silverstripe-travis-shared:config/provision/cwp-jobs-fixed.yml

env:
  global:
    - COMPOSER_ROOT_VERSION=2.5.x-dev
    - REQUIRE_RECIPE="$COMPOSER_ROOT_VERSION"
